// Generated by CoffeeScript 1.9.3
(function() {
  var dirname;

  dirname = require('path').dirname;

  exports.onComment = function(comment) {
    var path;
    path = dirname(comment.path);
    if (path !== '.' && !comment.namespace) {
      return comment.namespace = path;
    }
  };

}).call(this);
